### ISSUE TITLE
Always null in RequestBody update

### ISSUE THREAD

**Issue by veffhz** [SimonScholz/telegram-bot#1]
Hi, mr. Simon!

I try using your weather bot, but i always get null in BotController.java, when telegram api invoke webhook method. Object update always null (maybe jackson not bind field in Update class?)  :

public void webhook(@RequestBody Update update) 

Thanks!

**Comment by veffhz** [comment]
first problem - "Update" object has not setters and so not deserializing from json (with Jackson).
second problem - Jackson can not deserializing enum from json, becouse chat type "Private" in api instead "private" in json.

**Comment by SimonScholz** [comment]
Hi veffhz,

sorry for the long delay. You are absolutely right. In previous version of my bot implementation I created the API with lombok so I got getters and setters. Due to the problems you mentioned I dropped the pengrad third party lib, which has all the api types and created a new "telegram-bot-api" project. 

The api project is by far not complete, but it is working now.

Hopefully you're still interested in using my bot and even advancing it. Please feel free to fork it and send pull requests. For example for the missing fields and objects in the "telegram-bot-api" project.

Thanks for your feedback

**Comment by SimonScholz** [comment]
Looking forward to hear from you @veffhz 
I gonna close this issue for now
